input PageInput {
  name: String!,
  description: String,
  url: String!
}
type Page {
  id: ID!,
  name: String!,
  description: String,
  url: String!
}
type Query {
  pages:[Page!],
  page(id:ID!):Page
}
type Mutation{
  # createPage(name: String!,url: String!,desc: String):Page
  createPage(page : PageInput):Page
  updatePage(id:ID!, page : PageInput):Page
  deletePage(id : ID):String
}
